### ISSUE TITLE
Connecting to US Central FN server causes it to freeze up (connecting from asia)

### ISSUE THREAD

**Issue by Rustbuuket** [MSRevive/MasterSwordRebirth#69] opened 2022-06-24 04:29 UTC
Tested with RWGryphon.

Attempting to connect causes me to get stuck at "precaching resources," and upon checking the console, it says that I am missing bitmap fonts. Connecting causes the server to stop responding, and I end up timing out for connection.

> Missing bitmap font: gfx\vgui\fonts\1536_Basic Text.tga
> Missing bitmap font: gfx\vgui\fonts\1536_CommandMenu Text.tga
> Missing bitmap font: gfx\vgui\fonts\1536_Scoreboard Title Text.tga
> Missing bitmap font: gfx\vgui\fonts\1536_Scoreboard Small Text.tga
> Missing bitmap font: gfx\vgui\fonts\1536_Title Font.tga
> Missing bitmap font: gfx\vgui\fonts\1536_ID Text.tga
> Missing bitmap font: gfx\vgui\fonts\1536_Nrml.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlS.tga
> Missing bitmap font: gfx\vgui\fonts\1536_Lrge.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlI.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeI.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlIU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeIU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlB.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeB.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlBU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeBU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlBI.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeBI.tga
> Missing bitmap font: gfx\vgui\fonts\1536_NrmlBIU.tga
> Missing bitmap font: gfx\vgui\fonts\1536_LrgeBIU.tga

**Comment by SaintWish** [comment] 2022-06-24 08:26
Does this happen when trying to connect to any other servers like the US East one? Also, when this does happen can you show us what's in the ``log_cldll.log`` in the ``msrebirth/msrebirth`` directory, probably easiest to upload the log's content to this site https://www.toptal.com/developers/hastebin/about.md

**Comment by Rustbuuket** [comment] 2022-06-24 15:13
https://www.toptal.com/developers/hastebin/ifemulonay.md

**Comment by Rustbuuket** [comment] 2022-06-24 15:15
closing it was a misclick, sorry

The link above is the log file; attempting to connect to the US East server gave me an error regarding a mismatched .dll

I also forgot to mention that connecting to my friend via LAN did not result in any connection errors

**Comment by RWGryphon** [comment] 2022-06-24 15:46
> 

Correction: He connected to me VIA port 27015 on a non-FN server that I temporarily hosted.

Also as for the East server, I can’t join it either due to mismatching dll’s.

**Comment by SaintWish** [comment] 2022-06-24 18:42
I'm unable to reproduce this and I'm not sure why it's even happening to you. I'll leave this open though in-case others might have some idea.

**Comment by RWGryphon** [comment] 2022-06-24 18:44
> I'm unable to reproduce this and I'm not sure why it's even happening to you. I'll leave this open though in-case others might have some idea.

Maybe we could just restart the server? Highly doubt this would help but anything at this point is on the list. Still strange that Rust can join me without any issues. Could it be FN?

**Comment by SaintWish** [comment] 2022-06-25 01:06
FN doesn't affect loading at all, so I doubt it could be FN related. No one else from what I've seen has the same issue, though he could try now since there was a update pushed earlier.

**Comment by Rustbuuket** [comment] 2022-06-25 03:30
Hello! I've reinstalled and updated; still the same issue. I tried hosting my own server (locally), without FN, it ran normally. Connecting to the US East server results in the console stating "Server is running msrebirth. Restart in that game to connect."

**Comment by SaintWish** [comment] 2022-06-25 04:49
Closing in favor of MSRevive/MasterSwordRebirth#71

**Closed as not planned by SaintWish** 2022-06-25 04:49 UTC
