### ISSUE TITLE
Certain models turn white on map load

### ISSUE THREAD

**Issue by AldenDwyer** [MSRevive/MasterSwordRebirth#194] opened 2023-03-04 12:37 UTC
Not sure what happened, I loaded from a fresh open of the client and it is possible I alt+tabbed at least once before joining the server, but not during the loading screen. Some skins loaded in incorrectly (as pictured). Upon choosing a character there did not seem to be anything wrong with my littleguy.

![whiteboies](https://user-images.githubusercontent.com/125112622/222901381-b5d41c2c-11d3-47cb-b2e6-30e7c06931c1.png)
![whiteboiesconsole1](https://user-images.githubusercontent.com/125112622/222901383-3d8d095a-11db-499a-b9c4-53f6bd3c4672.png)
![whiteboiesconsole](https://user-images.githubusercontent.com/125112622/222901385-9c303f99-08fa-4dda-b06a-73d01c26df1d.png)

There was more lines in between the 2nd and 3rd image that were just the same messages of "Description too long" for a bunch of other things.

**Comment by SaintWish** [comment] 2023-03-23 08:47
Duplicate of this issue https://github.com/MSRevive/MasterSwordRebirth/issues/101

**Closed as not planned** 2023-03-23 08:47 UTC
